### ISSUE TITLE
Upload lesson

### ISSUE THREAD

**Issue by ankingcodes** [ankingcodes/typecode#10]
Create a new component where an user can upload a code file from their local machine. The user should be asked to add a title to that file, add language the code is in and then a field to upload the code. This code file should be saved to the database, as a `personal_lesson`.

**Comment by Piyush3436** [comment]
@ankingcodes  would like to work on this issue. Please assign this to me

**Comment by ankingcodes** [comment]
@Piyush3436 - Hey ! This issue is currently on hold because it depends on previous issues. You may explore the other issues.
