### ISSUE TITLE
SignIn form 

### ISSUE THREAD

**Issue by ankingcodes** [ankingcodes/typecode#7]
- [x] Currently, passwords are not encrypted using jwt on signup. Add jwt encryption on signup and use bcrypt for signin. (beginner)
- [x] Add validations for various fields on the Signup / Signin form. Use [semantic-UI](https://semantic-ui.com/elements/label.html) label pointers to show user for incorrect input (beginner)
- [x] Add Oauth login for Google and Github, preferably using [passport-js](http://www.passportjs.org/) (medium)
- [x] For the forget password link, create another route(`/app/account/password/reset`) using the react-router-dom config on `app.js`. Create a password reset form component with text similar to [this](https://www.instagram.com/accounts/password/reset/) using semantic UI components (keep design similar to Signup form). Try Re-using the component. On the server side, check if the email given by user on the card is present in the database. If present, send a mail to the email ID else show error that email is not registered. (HARD) (Discuss before proceeding)
- [x] Create a new component at a new route where an user can reset the password. The component should consist of two fields - password, confirm password, along with a Reset password button. On clicking the button, server should update the password of the corresponding email ID.  (HARD) (Discuss before proceeding)

**NOTE: (For NWOC students)**- Each of the issues can be treated as individual issues for which points would be given accordingly.

**Comment by pankajkumarbij** [comment]
Hello
I would like to contribute to the first issue(passwords are not encrypted using jwt on signup. Add jwt encryption on signup and use bcrypt for signin).

**Comment by luckykumarirai** [comment]
Hello 
I would like to contribute to the issue(Add validations for various fields on the Signup / Signin form. Use semantic-UI label pointers to show user for incorrect input (beginner))

**Comment by ankingcodes** [comment]
@pankajkumarbij - Hi ! Go ahead and send me a PR on it. I'll be happy to review !
@luckykumarirai - Go ahead with making the PR 👍🏻  !

**Comment by pankajkumarbij** [comment]
> @pankajkumarbij - Hi ! Go ahead and send me a PR on it. I'll be happy to review !

Hello 
I have sent a PR please review it.

**Comment by Sensrdt** [comment]
Hi!
Can I work on the third and fifth issues?

**Comment by ankingcodes** [comment]
@Sensrdt - Hello, go ahead and submit a PR !

**Comment by Sensrdt** [comment]
@ankingcodes
What should be the username and password for google signin user ?

**Comment by ankingcodes** [comment]
@Sensrdt - Could you create one for yourself while making the PR ? I'll change it with mine later. Use a config directory which contains a `keys.js` file where you can store the clientId, and clientsecret.

**Comment by luckykumarirai** [comment]
Hello
I have sent a PR on the second issue(Add validations for various fields on the Signup / Signin form. Use semantic-UI label pointers to show the user for incorrect input ).

**Comment by luckykumarirai** [comment]
Hello
I have sent a PR on the first issue(form validation) please review it.
