### ISSUE TITLE
User profile page

### ISSUE THREAD

**Issue by ankingcodes** [ankingcodes/typecode#8]
Create a profile page at `app/user/profile/:profile_id`, which will fetch details from server regarding registered user and display in a systematic way. The page should show the Name, Username, List of lessons completed, along with latest typing speed on a particular lesson attempted by user. The profile page can show many other data, such as a graph which can display typing speed improvements over past months (similar to what codechef / codeforces rating graph looks like). Use all your creativity on this issue, since the profile page should be the most attractive page of the app. 

**NOTE: (for NWOC student) - Discuss different features that can be introduced. The issue can be broken down into smaller issues and points can be awarded accordingly.**

**Comment by chiteshbansal** [comment]
hi I am interested to contribute to this issue, Can you provide me more info
like if uhave any predefined styling for the page and feature u want in it

**Comment by jaisai6** [comment]
Hey, would like to work on this issue.

**Comment by ankingcodes** [comment]
@chiteshbansal - I haven't decided on the styling yet, I'd love to know your ideas about it. You can take inspiration from profile pages of CodeForces, Leetcode etc. Take  note of the specifics I've given in the issue. 
@jaisai6 - Great to have you here ! 

Both of you can begin working on the issue, maybe discuss some designs for the profile page else just go ahead and make a PR.
